server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/carecenter?useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true&characterEncoding=utf8
    username: root
    password: 123456
      